<?php $this->headScript()->appendFile('/js/modules/validateCarriers.js') ?> 
<?php $disabled = ($this->dataUser['EDITAR']==0 && $this->dataUser['LECTURA']==1) ? 'disabled':'';?>
<div class="row panel-data">
    <input id="hRefLinkMain" type="hidden" value="/main/carriers/index" />
	<div class="span12">
		<!-- block -->
        <div class="block">
            <div class="navbar navbar-inner block-header">
                <div class="muted pull-left">
					<a href="javascript:backToMain()">
						<i class="icon-circle-arrow-left fa-1"></i></a>
                	Información del Transportisa</div>
            </div>
            <div class="block-content collapse in">
                <div class="span12">
					<?php if($this->dataUser['EDITAR']==0 && $this->dataUser['LECTURA']==0): ?>
						<div id="divpErrorLogin" class="alert alert-error" style="display:block;">
						  <button type="button" class="close" data-dismiss="alert">×</button>
						  <h4>Error</h4>
						  <div>Usted no tiene permiso para ver esta información</div>
						</div>						
					<?php else:?>	
					<!-- BEGIN FORM-->
					<?php if($disabled!='disabled'):?>
					<form method="POST" action="/main/carriers/getinfo" id="FormData" class="form-horizontal ">
					<?php endif;?>	
		                <input type="hidden" name="optReg" value="<?php echo ($this->idToUpdate>0) ? 'update': 'new';?>" />
		                <input type="hidden" name="catId" value="<?php echo $this->catId; ?>" />
		                
		                <?php if($this->resultOp=='okRegister'): ?>
		                    <div class="alert alert-success">
		                        <button class="close" data-dismiss="alert"></button>
		                        Datos se almacenaron correctamente.
		                    </div>                
		                <?php endif; ?>					
			                <fieldset>
			                    <div id="errorMsg" class="alert alert-error hide">
			                        <button class="close" data-dismiss="alert"></button>
			                        Alguno de los datos estan incorrectos,favor de verificarlos.
			                    </div>
			                    <div class="alert alert-success hide">
			                        <button class="close" data-dismiss="alert"></button>
			                        Datos correctos
			                    </div>
								<div class="control-group">
									<label class="control-label">Nombre<span class="required">*</span></label>
									<div class="controls">
										<input type="text" name="inputDescripcion"  class="span6 m-wrap" value="<?php echo @$this->data['DESCRIPCION']; ?>"  <?php echo $disabled;?> >
									</div>
								</div>		                    
								<div class="control-group">
									<label class="control-label">Razón Social<span class="required">*</span></label>
									<div class="controls">
										<input type="text" name="inputRazonSocial" class="span6 m-wrap" value="<?php echo @$this->data['RAZON_SOCIAL']; ?>"  <?php echo $disabled;?> >
									</div>
								</div>
								<div class="control-group">
									<label class="control-label">Dirección<span class="required">*</span></label>
									<div class="controls">
										<input name="inputDireccion" type="text" class="span6 m-wrap" value="<?php echo @$this->data['DIRECCION']; ?>" <?php echo $disabled;?> >
									</div>
								</div>
								<div class="control-group">
									<label class="control-label">Contacto:<span class="required">*</span></label>
									<div class="controls">
									  <input name="inputContacto" type="text" class="span6 m-wrap" value="<?php echo @$this->data['CONTACTO']; ?>" <?php echo $disabled;?> >
									</div>
								</div>
								<div class="control-group">
									<label class="control-label">Tel. Móvil:<span class="required">*</span></label>
									<div class="controls">
									  <input name="inputTelMovil" type="text" class="span6 m-wrap" value="<?php echo @$this->data['TEL_MOVIL']; ?>" <?php echo $disabled;?> >
									</div>
								</div>
								<div class="control-group">
									<label class="control-label">Tel. Fijo:<span class="required"></span></label>
									<div class="controls">
									  <input name="inputTelFijo" type="text" class="span6 m-wrap" value="<?php echo @$this->data['TEL_FIJO']; ?>" <?php echo $disabled;?> >
									</div>
								</div>
								<div class="control-group">
									<label class="control-label">Radio:<span class="required"></span></label>
									<div class="controls">
									  <input name="inputRadio" type="text" class="span6 m-wrap" value="<?php echo @$this->data['RADIO']; ?>" <?php echo $disabled;?> >
									</div>
								</div>
								<div class="control-group">
									<label class="control-label">Estatus<span class="required">*</span></label>
									<div class="controls">
										<select class="span6 m-wrap" name="inputStatus" <?php echo $disabled;?> >
											<?php echo $this->status; ?>
										</select>
									</div>
								</div>
								<?php if($disabled!='disabled'):?>
								<div class="form-actions">
									<button type="submit" class="btn btn-primary">Guardar</button>
									<button type="button" class="btn" onClick="javascript:backToMain()">Cancel</button>
								</div>
								<?php endif;?>
						</fieldset>
					<?php if($disabled!='disabled'):?>
					</form>
					<?php endif;?>
					<!-- END FORM-->																
					<?php endif;?>
				</div>
		    </div>
		</div>
	</div>
</div>  