        <div class="navbar navbar-fixed-top">
            <div class="navbar-inner">
                <div class="container-fluid">
                    <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse"> <span class="icon-bar"></span>
                     <span class="icon-bar"></span>
                     <span class="icon-bar"></span>
                    </a>
                    <a class="brand" href="/main/dashboard/index">
                        De Acero
                        <!--<img class="img" src="/images/clients/deacero.png">-->
                    </a>
                    <div class="nav-collapse collapse">
                        <ul class="nav pull-right">
                            <li class="dropdown">
                                <a href="#" role="button" class="dropdown-toggle" data-toggle="dropdown"> 
                                    <i class="icon-user"></i> admin@deacero.com<i class="caret"></i>
                                    <!--<br>
                                    Perfil: <b>super_admin</b>
                                    <br>
                                    Empresa: <b>De Acero</b>-->
                                </a>
                                <ul class="dropdown-menu">                                    
                                    <li>
                                        <a tabindex="-1" href="#">Cambiar Contraseña</a>
                                    </li>
                                    <li class="divider"></li>
                                    <li>
                                        <a tabindex="-1" href="/admin/main/logout">Salir</a>
                                    </li>
                                </ul>
                            </li>
                        </ul>

                        <ul class="nav">
                            <li class="<?php echo ($this->menu=='index')? 'active': '';?>">
                                <a href="/admin/dashboard/index">Inicio</a>
                            </li>
                            <li class="<?php echo ($this->menu=='catalogos')? 'active': '';?>">
                                <a href="/admin/admin/index">Catálogos</a>
                            </li>                         
                        </ul>
                    </div>
                    <!--/.nav-collapse -->
                </div>
            </div>
        </div>