<?php $this->headScript()->appendFile('/js/modules/gralTables.js') ?>   
<?php $this->headScript()->appendFile('/js/modules/validateUnits.js') ?>   
    <div class="row panel-data">
        <input id="hRefLinkEdit" type="hidden" value="/main/admin/getinfounit?idRow=" />
		<div class="span12">
			<!-- block -->
            <div class="block">
                <div class="navbar navbar-inner block-header">
                    <div class="muted pull-left">Unidades</div>
                </div>
                <div class="block-content collapse in">
                    <div class="span12">
                       <div class="table-toolbar">                            
                          <div class="btn-group">
                             <a href="/main/admin/getinfounit?catId=-1"><button class="btn btn-success"> Agregar <i class="icon-plus icon-white"></i></button></a>
                          </div>
                       </div>                        
                        <table cellpadding="0" cellspacing="0" border="0" class="table table-striped table-bordered" id="dataTable">
                            <thead>
                                <tr>
                                    <th>Nùmero</th>
                                    <th>Placas</th>
                                    <th>Descripción</th>
                                    <th>Opciones</th>
                                </tr>
                            </thead>
                            <tbody>                                
                                <?php foreach($this->datatTable as $key => $items): ?>  
                                <tr class="odd gradeX">
                                    <td><?php echo $items['IDENTIFICADOR']; ?></td>
                                    <td><?php echo $items['PLACAS']; ?></td>
                                    <td><?php echo $items['ECONOMICO']; ?></td>
                                    <td class="text-center "> 
                                        <a href="/main/admin/getinfounit?catId=<?php echo $items['ID_UNIDAD']; ?>"><button class="btn btn-primary"> <i class="icon-edit icon-white"></i></button></a>   
                                        <a href="javascript:confirmDelete('<?php echo $items['ID_UNIDAD']; ?>')"><button class="btn btn-danger"> <i class="icon-trash icon-white"></i></button></a>   
                                    </td>
                                </tr>    
                                <?php endforeach;?>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
            <!-- /block -->
		</div>
	</div>   

<div id="modalConfirmDelete" class="modal hide">
    <div class="modal-header">
        <button data-dismiss="modal" class="close" type="button">&times;</button>
        <h3>Atención!</h3>
    </div>
    <div class="modal-body">
        <p>¿Realmente desea eliminar este registro?</p>
    </div>
    <div class="modal-footer">
        <input type="hidden" id="inputDelete" value="-1"/>
        <a class="btn btn-primary" href="javascript:deleteRow();">Eliminar</a>
        <a data-dismiss="modal" class="btn" href="#">Cancelar</a>
    </div>
</div>    