<?php $this->headScript()->appendFile('/js/modules/gralTables.js') ?>     
    <div class="row bg-white panel-data">
        <input id="hRefLinkEdit" type="hidden" value="/main/admin/getinfounit?idRow=" />
		<div class="span12">
			<!-- block -->
            <div class="block">
                <div class="navbar navbar-inner block-header">
                    <div class="muted pull-left">Unidades</div>
                </div>
                <div class="block-content collapse in">
                    <div class="span12">
                       <div class="table-toolbar">                            
                          <div class="btn-group">
                             <a href="javascript:editDataTable(0)"><button class="btn btn-success"> Agregar <i class="icon-plus icon-white"></i></button></a>
                          </div>
                       </div>                        
                        <table cellpadding="0" cellspacing="0" border="0" class="table table-striped table-bordered" id="dataTable">
                            <thead>
                                <tr>
                                    <th>Nùmero</th>
                                    <th>Placas</th>
                                    <th>Descripción</th>
                                    <th>Opciones</th>
                                </tr>
                            </thead>
                            <tbody>
                                <tr class="odd gradeX">
                                    <td>3d3eqwed</td>
                                    <td>FRE878</td>
                                    <td>Unidad 1</td>
                                    <td class="text-center"> 
                                        <a href="javascript:editDataTable(1)"><button class="btn btn-primary"> <i class="icon-edit icon-white"></i></button></a>   
                                        <a href="javascript:confirmDelete(1)"><button class="btn btn-danger"> <i class="icon-trash icon-white"></i></button></a>   
                                    </td>
                                </tr>
                                
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
            <!-- /block -->
		</div>
	</div>   

<div id="modalTableEdit" class="modal hide">
    <div class="modal-header">
        <button data-dismiss="modal" class="close" type="button">&times;</button>
        <h3>Información de la Unidad</h3>
    </div>
    <div class="modal-body">
          <iframe class="custom-height-modal" id="iFrameModalAdd" src="" style="zoom:0.60" frameborder="0"></iframe>
    </div>
</div>

<div id="modalConfirmDelete" class="modal hide">
    <div class="modal-header">
        <button data-dismiss="modal" class="close" type="button">&times;</button>
        <h3>Atención!</h3>
    </div>
    <div class="modal-body">
        <p>¿Realmente desea eliminar este registro?</p>
    </div>
    <div class="modal-footer">
        <a data-dismiss="modal" class="btn btn-primary" href="#">Eliminar</a>
        <a data-dismiss="modal" class="btn" href="#">Cancelar</a>
    </div>
</div>    