<?php $this->headScript()->appendFile('/js/modules/monitor/tableSearch.js') ?>   
    <!-- block -->
    <div class="block">
        <div class="block-content collapse in">
                <table cellpadding="0" cellspacing="0" border="0" class="table table-striped table-bordered" id="dataTable">
                    <thead>
                        <tr>
                            <th>Nombre</th>
                        	<th>Perfil</th>                            
                            <th>Viajes por Atender</th>                            
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>                                
                        <?php foreach($this->dataTable as $key => $items): ?>  
                        <tr class="odd gradeX">
                            <td><?php echo $items['NOMBRE']; ?></td>
                            <td><?php echo $items['NAME_PERFIL']; ?></td>
                            <td><?php echo $items['TOTAL']; ?></td>
                            <td class="text-center"> 
                                <?php if($this->aModeAssign=='assign'):?>
                                    <a href="javascript:parent.assignValue(<?php echo $items['ID'];?>)">
                                <?php else:?>
                                    <a href="javascript:parent.re_assignValue(<?php echo $items['ID'];?>)">
                                <?php endif;?>
                                    <button class="btn-primary"> <i class=" icon-circle-arrow-down icon-white"></i></button>
                                    </button>
                                </a>
                            </td>
                        </tr>    
                        <?php endforeach;?>                                                                                                                                                                                          
                    </tbody>
                </table>
        </div>
    </div>
    <!-- /block -->