 <?php $this->headScript()->appendFile('/js/reports/repTravelDetail.js') ?>   
   <div class="row panel-data">
        <input id="hRefLinkEdit" type="hidden" value="/main/clients/getinfo?idRow=" />
        <div class="span12">
            <!-- block -->
            <div class="block">
                <div class="navbar navbar-inner block-header">
                    <div class="muted pull-left">Clientes</div>
                </div>
                <div class="block-content collapse in">
                </div>
            </div>
        </div>            
    </div>


    <div class="row panel-data">
        <input id="hRefLinkEdit" type="hidden" value="/main/clients/getinfo?idRow=" />
		<div class="span12">
			<!-- block -->
            <div class="block">
                <div class="navbar navbar-inner block-header">
                    <div class="muted pull-left">Clientes</div>
                </div>
                <div class="block-content collapse in">
                    <div class="span12">
                        <?php if($this->dataUser['INSERTAR']==1): ?>
                            <div class="table-toolbar">
                              <div class="btn-group">
                                 <a href="/main/clients/getinfo?catId=-1"><button class="btn btn-success"> Agregar <i class="icon-plus icon-white"></i></button></a>
                              </div>
                            </div>  
                        <?php endif;?>                          
                        <table cellpadding="0" cellspacing="0" border="0" class="table table-striped table-bordered" id="dataTable">
                            <thead>
                                <tr>
                                    <th>Empresa</th>
                                    <th>Sucursal</th>
                                    <th>Cliente</th>
                                    <th>Opciones</th>
                                </tr>
                            </thead>
                            <tbody>                                
                                <?php foreach($this->datatTable as $key => $items): ?>  
                                <tr class="odd gradeX">
                                    <td><?php echo $items['EMPRESA']; ?></td>
                                    <td><?php echo $items['SUCURSAL']; ?></td>
                                    <td><?php echo $items['NOMBRE'] ?></td>
                                    <td class="text-center">
                                        <?php if($this->dataUser['LECTURA']==1): ?>
                                            <a href="/main/clients/getinfo?catId=<?php echo $items['ID_CLIENTE']; ?>"><button class="btn btn-primary"> <i class="icon-eye-open icon-white"></i></button></a>   
                                        <?php endif;?> 
                                        <?php if($this->dataUser['ELIMINAR']==-1): ?>
                                            <a href="javascript:confirmDelete('<?php echo $items['ID_CLIENTE']; ?>')"><button class="btn btn-danger"> <i class="icon-trash icon-white"></i></button></a>
                                        <?php endif;?>
                                    </td>
                                </tr>    
                                <?php endforeach;?>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
            <!-- /block -->
		</div>
	</div>     