 <?php $this->headScript()->appendFile('/js/reports/jsValidateReport.js') ?>   
 <?php $options = Array('Ninguno','Id Viaje','Sucursal','Transportista'); ?>
   <div class="row panel-data">
        <input id="hRefLinkEdit" type="hidden" value="/main/clients/getinfo?idRow=" />
        <div class="span12">
            <!-- block -->
            <div class="block">
                <div class="navbar navbar-inner block-header">
                    <div class="muted pull-left">Bùsqueda</div>
                </div>
                <div class="block-content collapse in">
                    <form method="POST" action="/main/reports/index" id="FormData" class="form-horizontal ">
                        <input type="hidden" name="option" value="getReport" />
                        <fieldset>
                        <?php if(isset($this->saveSend) && @$this->saveSend==1): ?>
                            <div class="alert alert-success" >
                              <button type="button" class="close" data-dismiss="alert">×</button>
                              <h4>Atencion!</h4>
                              <div>El reporte que se muestra en pantalla, se enviará en breve al correo electrónico ingresado.</div>
                            </div>      
                        <?php endif;?>                            
                        <div class="row">
                            <div class="span4">
                                <div class="control-group">
                                    <label class="control-label">Inicio</label>
                                    <div class="controls">
                                          <input id="inputFechaIn" name="inputFechaIn" data-required="1"  type="text" class="form-control" value="<?php echo @$this->data['inputFechaIn']; ?>" id="inputDate">
                                    </div>
                                </div>              
                            </div>
                            <div class="span4">
                                <div class="control-group">
                                    <label class="control-label">Fin</label>
                                    <div class="controls">
                                        <input type="text" id="inputFechaFin" name="inputFechaFin" class="m-wrap" value="<?php echo (@$this->data['inputFechaFin']); ?>">
                                    </div>
                                </div>                          
                            </div>  
                            <div class="span4">
                                <div class="control-group">
                                    <label class="control-label">Estatus</label>
                                    <div class="controls">
                                        <select class="span12 m-wrap" name="inputStatus" >
                                        <option value="">Todos</option>
                                            <?php echo $this->aStatus ;?>
                                        </select>
                                    </div>
                                </div>                          
                            </div>                                                  
                        </div>
                        <div class="row">
                            <div class="span4">
                                <div class="control-group" style="display:<?php echo ($this->dataUser['ID_PERFIL'] == 1) ? 'block': 'none'; ?>;">
                                    <label class="control-label">Monitorista</label>
                                    <div class="controls">
                                        <select class="m-wrap" name="inputUserAssign" >
                                        <option value="">Todos</option>
                                            <?php echo $this->aUsuarios ;?>
                                        </select>
                                    </div>
                                </div>                          
                            </div>                              
                            <div class="span4">
                                <div class="control-group" style="display:<?php echo ($this->dataUser['ID_PERFIL'] == 1) ? 'block': 'none'; ?>;">
                                    <label class="control-label">Cliente</label>
                                    <div class="controls">
                                            <select class="m-wrap" name="inputCliente">
                                            <option value="">Todos</option>
                                                <?php echo $this->aEmpresas ;?>
                                            </select>
                                        </div>
                                </div>              
                            </div>

                            <div class="span4">
                                <!--
                                <div class="pull-right">            
                                    <button type="submit" class="btn btn-default bg-btn-send">Buscar</button>
                                </div> -->  
                            </div>                               
                        </div>   

                        <div class="row">
                            <div class="span4">
                                <div class="control-group">
                                    <label class="control-label">Enviar por Correo</label>
                                    <div class="controls">
                                        <select class="m-wrap" name="inputEnvio"  onChange="changeSendMail(this.value)">
                                            <?php echo $this->aEnvioMail ;?>
                                        </select>
                                    </div>
                                </div>                          
                            </div>                              
                            <div class="span4">
                                <div id="divMailSend" class="control-group" style="display:<?php echo (isset($this->data['inputEnvio']) == 1) ? 'block': 'none'; ?>;">
                                    <label class="control-label">Email</label>
                                    <div class="controls">
                                        <input id="inputEmail" name="inputEmail" data-required="1"  type="text" class="form-control" value="<?php echo @$this->data['inputEmail']; ?>" id="">
                                    </div>
                                </div>              
                            </div> 
                            <div class="span4">
                                <label class="control-label"></label>
                                <div class="controls">
                                        <button type="submit" class="btn btn-info btn-block bg-btn-send pull-right">Buscar</button>
                                </div>
                            </div>                                                       
                        </div>                                               
                        </fieldset>
                    </form>
                </div>
            </div>
        </div>            
    </div>

    <div class="row panel-data">
        <input id="hRefLinkEdit" type="hidden" value="/main/clients/getinfo?idRow=" />
		<div class="span12">
			<!-- block -->
            <div class="block">
                <div class="navbar navbar-inner block-header">
                    <div class="muted pull-left">Viajes</div>
                </div>
                <div class="block-content collapse in row-min-h">
                    <div class="span12">
                        <div class="button-excel-export">
                            <?php if(count($this->datatTable)>0): ?>
                                <div class="btn-group">
                                    <?php $urlExport = '?option=getReport&inputFechaIn='.@$this->data['inputFechaIn'].'&inputFechaFin='.@$this->data['inputFechaFin'].'&inputStatus='.@$this->data['inputStatus'].'&inputUserAssign='.@$this->data['inputUserAssign'].'&inputCliente='.@$this->data['inputCliente']; ?>
                                    <a target="_blank" href="/main/reports/exportsearch<?php echo $urlExport; ?>"><button class="btn btn-success"> Exportar <i class="icon-file icon-white"></i></button></a>
                                </div>
                            <?php endif;?>
                        </div>
                        <table cellpadding="0" cellspacing="0" border="0" class="table table-striped table-bordered" id="dataTable">
                            <thead>
                                <tr>
                                    <th>Cliente</th>
                                    <th>Clave Viaje</th>
                                    <th>Ruta</th>
                                    <th>ECO</th>
                                    <th>Fecha Prog. Inicio</th>
                                    <th>Fecha Prog. Fin</th>
                                    <th>Total Incidencias</th>
                                    <?php if($this->dataUser['ID_PERFIL']!=2): ?>
                                        <th>Asignado a</th>
                                    <?php endif;?>                                    
                                    <th>Estatus</th>
                                    <th>&nbsp;</th>
                                </tr>
                            </thead>
                            <tbody>                                
                                <?php foreach($this->datatTable as $key => $items): ?>  
                                <tr class="odd gradeX">
                                    <td><?php echo $items['DESC_EMPRESA']; ?></td>
                                    <td><?php echo $items['CLAVE']; ?></td>
                                    <td><?php echo $items['N_RUTA'] ?></td>
                                    <td><?php echo $items['IDENTIFICADOR']; ?></td>
                                    <td><?php echo $items['INICIO'] ?></td>
                                    <td><?php echo $items['FIN'] ?></td>
                                    <td><?php echo $items['INCIDENCIAS'] ?></td>
                                    <?php if($this->dataUser['ID_PERFIL']!=2): ?>
                                        <td><?php echo $items['MONITOR'] ?></td>
                                    <?php endif;?>                                    
                                    <td><?php echo $items['DES_STATUS'] ?></td>
                                    <td class="text-center">                                    
                                        <a href="/main/reports/exportdatatravel?travelID=<?php echo $items['ID_VIAJE'];?>" target="_blank"><button class="btn-success"> <i class="icon-download icon-white"></i></button></a>
                                    </td>
                                </tr>    
                                <?php endforeach;?>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
            <!-- /block -->
		</div>
	</div>     