<?php $this->headScript()->appendFile('/js/modules/contacts/validateContacts.js') ?> 
<?php $disabled = ($this->dataUser['EDITAR']==0 && $this->dataUser['LECTURA']==1) ? 'disabled':'';?>
<div class="row panel-data">
    <input id="hRefLinkMain" type="hidden" value="/admin/contacts/index" />
	<div class="span12">
		<!-- block -->
        <div class="block">
            <div class="navbar navbar-inner block-header">
                <div class="muted pull-left">
					<a href="javascript:backToMain()">
						<i class="icon-circle-arrow-left fa-1"></i></a>
                	Información del Contacto</div>
            </div>
            <div class="block-content collapse in">
                <div class="span12">
					<?php if($this->dataUser['EDITAR']==0 && $this->dataUser['LECTURA']==0): ?>
						<div id="divpErrorLogin" class="alert alert-error" style="display:block;">
						  <button type="button" class="close" data-dismiss="alert">×</button>
						  <h4>Error</h4>
						  <div>Usted no tiene permiso para ver esta información</div>
						</div>						
					<?php else:?>	
					<!-- BEGIN FORM-->
					<?php if($disabled!='disabled'):?>
					<form method="POST" action="/admin/contacts/getinfo" id="FormData" class="form-horizontal ">
					<?php endif;?>	
		                <input type="hidden" name="optReg" value="<?php echo ($this->idToUpdate>0) ? 'update': 'new';?>" />
		                <input type="hidden" name="catId" value="<?php echo $this->catId; ?>" />
		                
		                <?php if($this->resultOp=='okRegister'): ?>
		                    <div class="alert alert-success">
		                        <button class="close" data-dismiss="alert"></button>
		                        Datos se almacenaron correctamente.
		                    </div>                
		                <?php endif; ?>	
		                	<fieldset>                		
		                		<div class="span12 no-margin-left">
		                			<div class="span6">
										<div class="control-group">
											<label class="control-label">Nombre<span class="required">*</span></label>
											<div class="controls">
												<input name="inputName" autocomplete="off" type="text" class="m-wrap span12" value="<?php echo @$this->data['NOMBRE']; ?>" <?php echo $disabled;?> >
											</div>
										</div>		                				
		                			</div>
		                			<div class="span6">
										<div class="control-group">
											<label class="control-label">E-mail<span class="required">*</span></label>
											<div class="controls">
												<input name="inputEmail" autocomplete="off" type="text" class="m-wrap span12" value="<?php echo @$this->data['CORREO']; ?>" <?php echo $disabled;?> >
											</div>
										</div>		                				
		                			</div>	                			
		                		</div>
		                		<div class="span12 no-margin-left">

		                			<div class="span6">
										<div class="control-group">
											<label class="control-label">Estatus<span class="required">*</span></label>
											<div class="controls">
												<select class="span6 m-wrap"  autocomplete="off" name="inputStatus" <?php echo $disabled;?> >
													<?php echo $this->status; ?>
												</select>
											</div>
										</div>	                				
		                			</div>			                			
		                		</div>		                		
		                		<div class="span12 no-margin-left">
		                			<span><b>Enviar Notificaciones al contacto cuando:</b></span><br>
		                		</div>
		                		
		                		<div class="span12 no-margin-left">
		                			<div class="span6">
										<div class="control-group">
											<!--<label class="control-label">Incidencia<span class="required">*</span></label>-->
											<div class="controls">
												<input name="chkIncidencia"  type="checkbox" class="chkOn" <?php echo (@$this->data['INCIDENCIAS']	==1) ? 'checked="checked"': '';?> >&nbsp; Ocurra una incidencia (prioridad 1)<br>
												<input name="chkInicio"  	 type="checkbox" class="chkOn" <?php echo (@$this->data['INICIO_VIAJE']	==1) ? 'checked="checked"': '';?> >&nbsp; Inicie un Viaje <br>
												<input name="chkFin"  		 type="checkbox" class="chkOn" <?php echo (@$this->data['FIN_VIAJE']	==1) ? 'checked="checked"': '';?> >&nbsp; Finalice un Viaje <br>
											</div>
										</div>		                				
		                			</div>
		                			<div class="span6">
											                				
		                			</div>	                			
		                		</div>

								<div class="control-group">

								</div>
								<?php if($disabled!='disabled'):?>
								<div class="form-actions">
									<div class="pull-right">
										<button type="submit" class="btn btn-primary">Guardar</button>
										<button type="button" class="btn" onClick="javascript:backToMain()">Cancelar</button>
									</div>									
								</div>
								<?php endif;?>
						</fieldset>
					<?php if($disabled!='disabled'):?>
					</form>
					<?php endif;?>
					<!-- END FORM-->																
					<?php endif;?>
				</div>
		    </div>
		</div>
	</div>
</div>  