<?php $this->headScript()->appendFile('/js/modules/admin/validateIncidents.js') ?> 
<?php $disabled = ($this->dataUser['EDITAR']==0 && $this->dataUser['LECTURA']==1) ? 'disabled':'';?>
<div class="row panel-data">
    <input id="hRefLinkMain" type="hidden" value="/admin/incidents/index" />
	<div class="span12">
		<!-- block -->
        <div class="block">
            <div class="navbar navbar-inner block-header">
                <div class="muted pull-left">
					<a href="javascript:backToMain()">
						<i class="icon-circle-arrow-left fa-1"></i></a>
                	Información de la incidencia</div>
            </div>
            <div class="block-content collapse in">
                <div class="span12">
					<?php if($this->dataUser['EDITAR']==0 && $this->dataUser['LECTURA']==0): ?>
						<div id="divpErrorLogin" class="alert alert-error" style="display:block;">
						  <button type="button" class="close" data-dismiss="alert">×</button>
						  <h4>Error</h4>
						  <div>Usted no tiene permiso para ver esta información</div>
						</div>						
					<?php else:?>	
					<!-- BEGIN FORM-->
					<?php if($disabled!='disabled'):?>
					<form method="POST" action="/admin/incidents/getinfo" id="FormData" class="form-horizontal ">
					<?php endif;?>	
		                <input type="hidden" name="optReg" value="<?php echo ($this->idToUpdate>0) ? 'update': 'new';?>" />
		                <input type="hidden" name="catId" value="<?php echo $this->catId; ?>" />
		                
		                <?php if($this->resultOp=='okRegister'): ?>
		                    <div class="alert alert-success">
		                        <button class="close" data-dismiss="alert"></button>
		                        Datos se almacenaron correctamente.
		                    </div>                
		                <?php endif; ?>					
			                <fieldset>
			                    <div id="errorMsg" class="alert alert-error hide">
			                        <button class="close" data-dismiss="alert"></button>
			                        Alguno de los datos estan incorrectos,favor de verificarlos.
			                    </div>
			                    <div class="alert alert-success hide">
			                        <button class="close" data-dismiss="alert"></button>
			                        Datos correctos
			                    </div>
								<div class="control-group">
									<label class="control-label">Nombre<span class="required">*</span></label>
									<div class="controls">
										<input type="text" name="inputDescripcion" autocomplete="off" class="span6 m-wrap upperClass" value="<?php echo @$this->data['DESCRIPCION']; ?>"  <?php echo $disabled;?> >
									</div>
								</div>		                    
								<div class="control-group">
									<label class="control-label">Prioridad Alta<span class="required">*</span></label>
									<div class="controls">
										<select class="span6 m-wrap" name="inputPrioridad" autocomplete="off"  <?php echo $disabled;?> >
											<?php echo $this->prioridad; ?>
										</select>
									</div>
								</div>
								<div class="control-group">
									<label class="control-label">Enviar correo<span class="required">*</span></label>
									<div class="controls">
										<select class="span6 m-wrap" name="inputCorreo" autocomplete="off"  <?php echo $disabled;?> >
											<?php echo $this->enviarmail; ?>
										</select>
									</div>
								</div>
								<div class="control-group">
									<label class="control-label">Tiene Costo Extra<span class="required">*</span></label>
									<div class="controls">
										<select class="span6 m-wrap" name="inputCosto" autocomplete="off"  onChange="addCost(this.value)" <?php echo $disabled;?> >
											<?php echo $this->bPrecioExt; ?>
										</select>
									</div>
								</div>								
								<div id="divCost" class="control-group" style="display:<?php echo (@$this->data['COSTO_EXTRA']==1) ? 'block' : 'none'; ?>">
									<label class="control-label">Costo ($)<span class="required">*</span></label>
									<div class="controls">
										<input type="text" name="inputCextra"  autocomplete="off" class="span6 m-wrap upperClass" value="<?php echo @$this->data['PRECIO_EXTRA']; ?>"  <?php echo $disabled;?> >
										<input type="hidden" id="inputCostoExtra" value="<?php echo @$this->data['COSTO_EXTRA']; ?>">
									</div>
								</div>
								
								<?php if($disabled!='disabled'):?>
								<div class="form-actions">
									<button type="submit" class="btn btn-primary">Guardar</button>
									<button type="button" class="btn" onClick="javascript:backToMain()">Cancelar</button>
								</div>
								<?php endif;?>
						</fieldset>
					<?php if($disabled!='disabled'):?>
					</form>
					<?php endif;?>
					<!-- END FORM-->																
					<?php endif;?>
				</div>
		    </div>
		</div>
	</div>
</div>  