<?php $this->headScript()->appendFile('https://maps.googleapis.com/maps/api/js?v=3.exp&sensor=false') ?>
<?php $this->headScript()->appendFile('/js/modules/travels/mPrincipal.js') ?>   
    <div class="row panel-data">
        <input id="hRefLinkEdit" type="hidden" value="/admin/extras/getinfo?idRow=" />
        <div class="span12">
            <!-- block -->
            <div class="block row-min-h600">
                <div class="navbar navbar-inner block-header">
                    <div class="muted pull-left"> Mis Viajes</div>
                    <p class="pull-right"> 
                        <a href="/travels/main/newtravel">
                           <button class="btn btn-success"><i class="icon-plus icon-white"></i> Nuevo Viaje</button>
                        </a>
                    </p>
                </div>
                <div class="block-content collapse in">
                    <div class="span12">                       
                        <ul id="tabs" class="nav nav-tabs bg-white" data-tabs="tabs">
                            <li class="active"><a href="#tab" data-toggle="tab">Viajes Pendientes</a></li>     
                            <li><a href="#tab2" data-toggle="tab">Viajes en Curso</a></li>
                            <li><a href="#tab3" data-toggle="tab">Viajes Cerrados</a></li>
                            <li><a href="#tab4" data-toggle="tab">Incidencias</a></li>
                        </ul>
                        <div id="my-tab-content" class="tab-content bg-white">
                            <div class="tab-pane active" id="tab">
                                <table cellpadding="0" cellspacing="0" border="0" class="table table-striped table-bordered" id="dataTable">
                                    <thead>
                                        <tr>
                                            <th>Cliente</th>    
                                            <th>Clave Viaje</th>
                                            <th>Ruta</th>
                                            <th>ECO</th>
                                            <th>Fecha Prog. Inicio</th>
                                            <th>Fecha Prog. Fin</th>
                                            <th>Estatus</th>
                                            <th> </th>
                                        </tr>
                                    </thead>
                                    <tbody>                                
                                        <?php foreach($this->aViajesNew as $key => $items): ?>  
                                        <tr class="odd gradeX">
                                            <td><?php echo $items['CLIENTE']; ?></td>
                                            <td><?php echo $items['CLAVE']; ?></td>     
                                            <td><?php echo $items['DES_RUTA']; ?></td>
                                            <td><?php echo $items['IDENTIFICADOR']; ?></td>
                                            <td><?php echo $items['INICIO']; ?></td>
                                            <td><?php echo $items['FIN']; ?></td>
                                            <td><?php echo $items['STATUS_VIAJE'];?></td>
                                            <td class="text-center">
                                                <a onClick="infoTravel(<?php echo $items['ID_VIAJE']; ?>);">
                                                    <button class="btn-info"> <i class="icon-info-sign icon-white"></i></button>
                                                </a>
                                            </td>
                                        </tr>    
                                        <?php endforeach;?>
                                    </tbody>
                                </table>                                
                            </div>
                            <div class="tab-pane" id="tab2">
                                <table cellpadding="0" cellspacing="0" border="0" class="table table-striped table-bordered" id="dataTable">
                                    <thead>
                                        <tr>
                                            <th>Cliente</th>    
                                            <th>Clave Viaje</th>                        
                                            <th>Ruta</th>
                                            <th>ECO</th>
                                            <th>Fecha Prog. Inicio</th>
                                            <th>Fecha Prog. Fin</th>
                                            <th>Estatus</th>
                                            <th> </th>
                                        </tr>
                                    </thead>
                                    <tbody>                                
                                        <?php foreach($this->aViajesCurrent as $key => $items): ?>  
                                        <tr class="odd gradeX">
                                            <td><?php echo $items['CLIENTE']; ?></td>
                                            <td><?php echo $items['CLAVE']; ?></td>     
                                            <td><?php echo $items['DES_RUTA']; ?></td>  
                                            <td><?php echo $items['IDENTIFICADOR']; ?></td>
                                            <td><?php echo $items['INICIO']; ?></td>
                                            <td><?php echo $items['FIN']; ?></td>
                                            <td><?php echo $items['STATUS_VIAJE'];?></td>
                                            <td class="text-center">
                                                <a onClick="infoTravel(<?php echo $items['ID_VIAJE']; ?>);">
                                                    <button class="btn-info"> <i class="icon-info-sign icon-white"></i></button>
                                                </a>
                                            </td>
                                        </tr>    
                                        <?php endforeach;?>
                                    </tbody>
                                </table>                                
                            </div>
                            <div class="tab-pane" id="tab3">

                                <table cellpadding="0" cellspacing="0" border="0" class="table table-striped table-bordered" id="dataTable">
                                    <thead>
                                        <tr>
                                            <th>Cliente</th>    
                                            <th>Clave Viaje</th>
                                            <th>Ruta</th>
                                            <th>ECO</th>
                                            <th>Fecha Prog. Inicio</th>
                                            <th>Fecha Prog. Fin</th>
                                            <th>Estatus</th>
                                            <th> </th>
                                        </tr>
                                    </thead>
                                    <tbody>                                
                                        <?php foreach($this->aViajesFinish as $key => $items): ?>  
                                        <tr class="odd gradeX">
                                            <td><?php echo $items['CLIENTE']; ?></td>
                                            <td><?php echo $items['CLAVE']; ?></td>
                                            <td><?php echo $items['DES_RUTA']; ?></td>
                                            <td><?php echo $items['IDENTIFICADOR']; ?></td>
                                            <td><?php echo $items['INICIO']; ?></td>
                                            <td><?php echo $items['FIN']; ?></td>
                                            <td><?php echo $items['STATUS_VIAJE'];?></td>
                                            <td class="text-center">
                                                <a onClick="infoTravel(<?php echo $items['ID_VIAJE']; ?>);">
                                                    <button class="btn-info"> <i class="icon-info-sign icon-white"></i></button>
                                                </a>
                                            </td>
                                        </tr>    
                                        <?php endforeach;?>
                                    </tbody>
                                </table>    

                            </div> 
                            <div class="tab-pane" id="tab5">                                                                                   
                                <table cellpadding="0" cellspacing="0" border="0" class="table table-striped table-bordered" id="dataTable2">
                                    <thead>
                                        <tr>
                                            <th>Clave Viaje</th>
                                            <th>Incidencia</th>
                                            <th>Prioridad</th>
                                            <th></th>
                                        </tr>
                                    </thead>
                                    <tbody>                                
                                        <?php foreach($this->aIncidencias as $key => $items): ?>  
                                        <tr class="odd gradeX">
                                            <td><?php echo $items['CLAVE']; ?></td>
                                            <td><?php echo $items['DESC_INCIDENCIA']; ?></td>
                                            <td><?php echo $items['PRIORIDAD'] ?></td>
                                            <td class="text-center">
                                                <a onClick="infoTravel(<?php echo $items['ID_VIAJE']; ?>);">
                                                    <button class="btn-success"> <i class="icon-download icon-white"></i></button>
                                                </a>
                                            </td>
                                        </tr>    
                                        <?php endforeach;?>
                                    </tbody>
                                </table>                                       
                            </div>
                        </div>    
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Modal -->
    <div class="modal fade hide modal-lg" id="myModalTravel" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true" >
      <div class="modal-dialog ">
        <div class="modal-content">
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
            <h4 class="modal-title" >Información del Viaje</h4>
          </div>
          <div class="modal-form i-body">             
            <img id="loader1" class="offset4" src="/images/assets/loading.gif" alt="loading gif"/>
            <iframe class="hmodal550" id="iFrameModaltravel" src="" style="zoom:0" frameborder="0"></iframe>
          </div>
        </div>
      </div>
    </div>    