<?php $this->headScript()->appendFile('https://maps.googleapis.com/maps/api/js?v=3.exp&sensor=false') ?>
<?php $this->headScript()->appendFile('/js/modules/travels/mPrincipal.js') ?>   
<div class="row-fluid">
    <div class="span6">
        <div class="block row-min-h600">
            <div class="navbar navbar-inner block-header">
                <div class="muted pull-left">Viajes En Curso</div>
            </div>
            <div class="block-content collapse in">
                <div class="span12">
                    <div class="table-toolbar">
                      <div class="btn-group">
                         <a href="/travels/main/newtravel"><button class="btn btn-success"> Nuevo Viaje <i class="icon-plus icon-white"></i></button></a>
                      </div>
                    </div>  
                    <table cellpadding="0" cellspacing="0" border="0" class="table table-striped table-bordered" id="dataTable">
                        <thead>
                            <tr>
                                <th>Clave Viaje</th>
                                <th>Cliente</th>
                                <th>Eco</th>
                                <th>Estatus Pago</th>
                                <th> </th>
                            </tr>
                        </thead>
                        <tbody>                                
                            <?php foreach($this->aViajes as $key => $items): ?>  
                            <tr class="odd gradeX">
                                <td><?php echo $items['CLAVE']; ?></td>
                                <td><?php echo $items['CLIENTE']; ?></td>
                                <td><?php echo $items['ECONOMICO']; ?></td>
                                <td><?php echo $items['E_PAGO'];?></td>
                                <td class="text-center">
                                    <a onClick="infoTravel(<?php echo $items['ID_VIAJE']; ?>);">
                                        <button class="btn-success"> <i class="icon-download icon-white"></i></button>
                                    </a>
                                </td>
                            </tr>    
                            <?php endforeach;?>
                        </tbody>
                    </table>
                </div>
            </div>
        </div> 
    </div>
    <div class="span6">
        <div class="block row-min-h600">
            <div class="navbar navbar-inner block-header">
                <div class="muted pull-left">Incidencias</div>
            </div>
            <div class="block-content collapse in">
                <div class="span12">  
                    <div class="table-toolbar">
                      <div class="btn-group">
                         <!--<a href="/admin/carriers/getinfo?catId=-1"><button class="btn btn-success"> Agregar <i class="icon-plus icon-white"></i></button></a>-->
                      </div>
                    </div>                                        
                    <table cellpadding="0" cellspacing="0" border="0" class="table table-striped table-bordered" id="dataTable2">
                        <thead>
                            <tr>
                                <th>Clave Viaje</th>
                                <th>Incidencia</th>
                                <th>Prioridad</th>
                                <th></th>
                            </tr>
                        </thead>
                        <tbody>                                
                            <?php foreach($this->aIncidencias as $key => $items): ?>  
                            <tr class="odd gradeX">
                                <td><?php echo $items['CLAVE']; ?></td>
                                <td><?php echo $items['DESC_INCIDENCIA']; ?></td>
                                <td><?php echo $items['PRIORIDAD'] ?></td>
                                <td class="text-center">
                                    <a onClick="infoTravel(<?php echo $items['ID_VIAJE']; ?>);">
                                        <button class="btn-success"> <i class="icon-download icon-white"></i></button>
                                    </a>
                                </td>
                            </tr>    
                            <?php endforeach;?>
                        </tbody>
                    </table>                   
                </div>
            </div>
        </div>         
    </div>    
</div>    

<div class="row-fluid">
    <div class="span12">
        <div class="block row-min-h600">
            <div class="navbar navbar-inner block-header">
                <div class="muted pull-left">Viajes Pendientes de Pago</div>
            </div>
            <div class="block-content collapse in">
                <div class="span12">  
                    <div class="table-toolbar">
                      <div class="btn-group">
                         <!--<a href="/admin/carriers/getinfo?catId=-1"><button class="btn btn-success"> Agregar <i class="icon-plus icon-white"></i></button></a>-->
                      </div>
                    </div>                                        
                    <table cellpadding="0" cellspacing="0" border="0" class="table table-striped table-bordered" id="dataTable">
                        <thead>
                            <tr>
                                <th>Clave Viaje</th>
                                <th>Cliente</th>
                                <th>Eco</th>
                                <th>Estatus Pago</th>
                                <th> </th>
                            </tr>
                        </thead>
                        <tbody>                                
                            <?php foreach($this->aViajes as $key => $items): ?>  
                            <tr class="odd gradeX">
                                <td><?php echo $items['CLAVE']; ?></td>
                                <td><?php echo $items['CLIENTE']; ?></td>
                                <td><?php echo $items['ECONOMICO']; ?></td>
                                <td><?php echo $items['E_PAGO'];?></td>
                                <td class="text-center">
                                    <a onClick="/travels/main/resume?catId=<?php echo $items['ID_VIAJE'];?>">
                                        <button class="btn-success"> <i class="icon-white"></i></button>
                                    </a>
                                </td>
                            </tr>    
                            <?php endforeach;?>
                        </tbody>
                    </table>                 
                </div>
            </div>
        </div>         
    </div>
</div>

<div class="modal fade hide modal-lg" id="myModalTravel" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true" >
  <div class="modal-dialog ">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title" >Información del Viaje</h4>
      </div>
      <div class="modal-form i-body">     
        <img id="loader1" class="offset4" src="/images/assets/loading.gif" alt="loading gif"/>                   
        <iframe class="hmodal550" id="iFrameModaltravel" src="" style="zoom:0" frameborder="0"></iframe>
      </div>
    </div>
  </div>
</div>

<div class="modal fade hide modal-lg" id="ModalNewTravel" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true" >
  <div class="modal-dialog ">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title" >Nuevo Viaje</h4>
      </div>
      <div class="modal-form i-body">     
        <img id="loader2" class="offset4" src="/images/assets/loading.gif" alt="loading gif"/>                   
        <iframe class="hmodal550" id="iFrameNewtravel" src="" style="zoom:0" frameborder="0"></iframe>
      </div>
    </div>
  </div>
</div>