<div class="block-content">
    <div class="row-fluid">
        <!-- block -->
        <div class="block">
            <div class="navbar navbar-inner block-header">
                <div class="muted pull-left">Respuesta de Pago</div>
            </div>
            <div class="block-content collapse in">
                <div class="span12">
	                <div class="alert alert-success alert-dismissable" style="display:block;">
	                    <i class="fa fa-check"></i>	                        
	                    <b>!Atención¡</b> Su pago se ha procesado correctamente.<br/>
	                    Para ir al panel principal de viajes dar click <a href="/">AQUI</a>
	                </div>	
                </div>
            </div>
        </div>
        <!-- /block -->
    </div>
</div>