<?php $this->headScript()->appendFile('/js/modules/travels/payTravel.js') ?> 
<div class="row panel-data">
    <input id="hRefLinkMain" type="hidden" value="/travels/main/index" />
	<div class="span12">
        <div class="block">
            <div class="navbar navbar-inner block-header">
                <div class="muted pull-left">
					Resumen del Viaje
				</div>
            </div>
            <div class="block-content collapse in">
            	<div class="span12">      		
					<form method="POST" action="/travels/main/paytravel" id="FormData" class="form-horizontal ">
		                <input type="hidden" name="optReg" value="registerTravel" />            			
            			<fieldset>		                
		                	<div class="span12 no-margin-left">
		                		<h4>Total Viaje</h4>
		                		<table cellpadding="0" cellspacing="0" border="0" class="table table-striped table-bordered" id="dataTable">
		                			<tr>
		                				<td class="text-center">Id Viaje</td>
		                				<td>Ruta</td>
		                				<td class="text-center">Tipo de Viaje</td>
		                				<td class="text-center">Horas de Viaje</td>
		                				<td class="text-center">Precio Hora</td>
		                				<td class="text-center span2">Total</td>
		                			</tr>
		                			<tr>
		                				<td class="text-center"><?php echo $this->dataTravel['CLAVE']; ?></td>
		                				<td><?php echo $this->aMoreInfo['DESCRIPCION']; ?></td>
		                				<td class="text-center"><?php echo $this->aTipoViaje['T_DESC']; ?></td>
		                				<td class="text-center"><?php echo $this->aMoreInfo['TIEMPO_ESTIMADO']; ?></td>		                				
		                				<td class="text-center">$ <?php echo number_format($this->aTipoViaje['COSTO'], 2, '.', ' '); ?></td>
		                				<td class="text-center span2">$ <?php echo number_format(($this->aMoreInfo['TIEMPO_ESTIMADO'] * $this->aTipoViaje['COSTO']), 2, '.', ' '); ?>
		                					<input type="hidden" id="itotalViaje" value="<?php echo ($this->aMoreInfo['TIEMPO_ESTIMADO'] * $this->aTipoViaje['COSTO']); ?>"/>
		                				</td>
		                			</tr>			                					                			                			
		                		</table>
		                	</div>		                	
		                	<div class="span12 no-margin-left">
		                		<h4>Servicios Extras</h4>
		                		<table cellpadding="0" cellspacing="0" border="0" class="table table-striped table-bordered" id="dataTable">
		                			<tr>		                				
		                				<td>Descripcion</td>
		                				<td class="text-center">Costo</td>                				
		                				<td class="text-center">Cantidad</td>
		                				<td class="text-center span2">Total</td>
		                			</tr>
		                			<?php $sumaIncidencias = 0;?>
		                			<?php foreach($this->aIncidencias as $key => $items): ?>
		                				<?php $sumaIncidencias += $items['TOTAL'];?>
		                			<tr>
		                				<td class=""><?php echo $items['DESCRIPCION']; ?></td>
										<td class="text-center">$ <?php echo number_format($items['PRECIO_EXTRA'], 2, '.', ' '); ?></td>
										<td class="text-center"><?php echo number_format($items['CANTIDAD'], 2, '.', ' '); ?></td>
										<td class="text-center">$ <?php echo number_format($items['TOTAL'], 2, '.', ' '); ?></td>		                				
		                			</tr>
		                			<?php endforeach;?>
		                			<tr>
		                				<td class="text-right" colspan="3"><b>Total Extras</b></td>
		                				<td class="text-center"><span id="lbTotal">$ <?php echo number_format($sumaIncidencias, 2, '.', ' '); ?></span>
		                				</td>
		                			</tr>                			
		                		</table>
		                	</div>

		                	<div class="span12 no-margin-left">
		                		<h4>Resumen del Pago</h4>
		                		<table cellpadding="0" cellspacing="0" border="0" class="table table-striped table-bordered" id="dataTable">
		                			<tr>
		                				<td class="text-right" colspan="3"><b>Total Viaje</b></td>
		                				<?php $iTotalViaje = ($this->aMoreInfo['TIEMPO_ESTIMADO'] * $this->aTipoViaje['COSTO']);?>
		                				<td class="text-center span2"><span id="lbTotal">$ <?php echo number_format($iTotalViaje, 2, '.', ' '); ?></span>
											<input type="hidden" id="inputTotalTravel" name="inputTotalTravel" value="0" />
		                				</td>
		                			</tr>
		                			<tr>
		                				<td class="text-right" colspan="3"><b>Total Incidencias</b></td>
		                				<td class="text-center"><span id="lbTotalTravel">$ <?php echo number_format($sumaIncidencias, 2, '.', ' '); ?></span>
											<input type="hidden" id="inputTotalInc" name="inputTotalInc" value="0" />
		                				</td>
		                			</tr>		

		                			<tr>
		                				<td class="text-right" colspan="3"><b>Total por Pagar</b></td>
		                				<td class="text-center"><span id="lbTotalBig">$ <?php echo number_format(($sumaIncidencias+$iTotalViaje), 2, '.', ' '); ?></span>
		                					<input type="hidden" id="inputBigTotal" name="inputBigTotal" value="0" />
		                				</td>
		                			</tr>	                				                					                			                			
		                		</table>
		                	</div>		                	
						</fieldset>                	
					</form>
					<?php if($this->dataUser['COBRAR_VIAJES']==1):?>
						<div class="">
					    	<div class="span12">
								<div class="text-center">
									<?php if($this->dataTravel['ID_ESTATUS_PAGO']!=2): ?>
										<form action='https://www.paypal.com/cgi-bin/webscr' method='post'>
											<input type='hidden' name='cmd' value='_xclick'>
											<input type='hidden' name='business' value='administracion@grupouda.com.mx'>
											<input type='hidden' name='item_name' value='Monitoreo Viaje #<?php echo $this->dataTravel['ID_VIAJE']; ?>'>
											<input type='hidden' name='item_number' value='travel_<?php echo $this->dataTravel['ID_VIAJE']; ?>'>
											<input type='hidden' name='amount' value='<?php echo ($sumaIncidencias+$iTotalViaje) ;?>'>									
											<input type='hidden' name='clt_manage' value='1'>
											<input type='hidden' name='no_shipping' value='0'>
											<input type='hidden' name='no_note' value='1'>
											<input type='hidden' name='currency_code' value='MXN'>
											<input type='hidden' name='lc' value='MX'>
											<input type='hidden' name='bn' value='PP-BuyNowBF'>
					                        <input type="hidden" name="return" value="http://viajes.grupouda.com.mx/main/processpayments/okpayment"?>
					                        <input type="hidden" name="cancel_return" value="http://viajes.grupouda.com.mx/main/processpayments/declinepay"?>
					                        <input type="hidden" name="notify_url" value="http://viajes.grupouda.com.mx/main/processpayments/receivepayment">
											<input type="image" src="https://www.sandbox.paypal.com/es_XC/MX/i/btn/btn_paynowCC_LG.gif" border="0" name="submit" alt="PayPal, la forma más segura y rápida de pagar en línea.">
											<img alt="" border="0" src="https://www.sandbox.paypal.com/es_XC/i/scr/pixel.gif" width="1" height="1">
										</form>										
									<?php else: ?>	
										<a class="/travels/main/index"><button class="btn btn-success bg-btn-send"> PANEL DE VIAJES </button></a>
									<?php endif;?>	
								</div>    
					    	</div>						
						</div>	
					<?php endif;?>
                </div>
            </div>
        </div>
    </div>
</div>