<div class="block-content">
    <div class="row-fluid">
        <!-- block -->
        <div class="block">
            <div class="navbar navbar-inner block-header">
				<div class="muted pull-left">Respuesta de Pago</div>
            </div>
            <div class="block-content collapse in">
                <div class="span12">
					<div class="alert alert-error" style="display:block;">
						<button type="button" class="close" data-dismiss="alert">×</button>
						<b>!Atención Error¡</b>
						<div>Su pago no pudo ser procesado, favor de intentarlo mas tarde.</div>
					</div>               
                </div>
            </div>
        </div>
    </div>
</div>