<?php $this->headScript()->appendFile('/js/modules/validateRecoveryPass.js') ?> 
<body id="login">
  <div class="container">
    <div class="span5 offset3 login-form">
        <div class="navbar navbar-inner block-header">
            <div class="muted pull-left">Nueva Contraseña</div>
        </div>
        <div class="block-content collapse in">
         <?php if(@$this->aErrors['errorConfig']):?>
              <div class="alert alert-danger" style="display:block;">
                <button type="button" class="close" data-dismiss="alert">×</button>
                <h4>Error</h4>
                <div>Información recibida incorrecta, favor de contactar con su adminsitrador.</div>
                <br/>
                  <a href="/main/main/index">Regresar</a>
              </div>
          <?php endif;?>    

          <?php if($this->result=='updated'):?>
              <div class="alert alert-success alert-dismissable">
                  <i class="fa fa-check"></i>
                  <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                  <b>!Atención¡</b> La contraseña se ha cambiado correctamente.<br/>
                  <a href="/login/main/index">Ingresar al sistema</a>
              </div>
          <?php elseif(!isset($this->aErrors['errorConfig'])):?>
            <form method="POST" action="/main/recover/recoverresq?keyResetToker=<?php echo ($this->dataIn['keyResetToker']);?>" id="FormData" class="form-horizontal ">
                <input type="hidden" id="optReg" name="optReg" value="reset" />
                <input type="hidden" name="idReset" value="<?php echo ($this->catId);?>" />

                <fieldset>
                    <div class="control-group">
                      <label class="control-label">Contraseña<span class="required">*</span></label>
                      <div class="controls">
                        <input id="inputPassword" name="inputPassword" autocomplete="off" type="password" class="m-wrap span3" >
                      </div>
                    </div>
                    <div class="control-group">
                      <label class="control-label">Confirmar Contraseña<span class="required">*</span></label>
                      <div class="controls">
                        <input id="inputCpassword" name="inputCpassword" autocomplete="off" type="password" class="m-wrap span3" >
                      </div>
                    </div>                      
                    <div class="text-right">                
                      <button type="submit" class="btn btn-primary" type="button" >Recuperar</button>  
                    </div>
                </fieldset>
              </form>
          <?php endif;?>
        </div>
    </div>
  </div> <!-- /container -->
</body>